### ISSUE TITLE
iOS 8 issue

### ISSUE THREAD

**Issue by cannyboy** [enryold/UITabBarItem-CustomBadge#1]
The badge appears behind the badge icon on iOS 8.

**Comment by enryold** [comment]
Thank you, i've not tested with iOS 8. I will try to find a solution!

**Comment by cannyboy** [comment]
Thanks

**Comment by aslisabanci** [comment]
I've tried bringing the custom label to the front with bringSubviewToFront, or inserting the custom label to the same index as the replaced badgeview but these didn't work for me under iOS 8. 

Thanks for sharing your code, btw! @enryold

**Comment by enryold** [comment]
Hi guys.
I've fixed with a dirty method cause I use this category for an app that i have to submit as soon as possibile. :|

@aslisabanci bringSubviewToFront doesn't work cause I think that the iOS framework brings to front only the content under _UIBadgeView view. 

With this assumption i added the custom label under _UIBadgeView without hide it. And it works..
In this way the new label is over the old badge view, and in some cases the old borders can be visible. 
To fix this i added an offset to make the new badge label a little big. 

I know.. It's dirty... but still works..! :)

**Comment by tavsan** [comment]
Yeah, dirty but at least you could get a result :) We can let each other know if we can come up with a better solution.

Cheers!

**Comment by enryold** [comment]
Ok Guys, i've just added a clean fix for the border of UIBadgeView.
Now it's all ok without dirty solutions :P

**Comment by cannyboy** [comment]
awesome work. 
In my case I had changed the class to overlay a custom view, which was was bigger than the UIBadgeView, so I had to do:

```
sv.layer.masksToBounds = NO;
```

.. before adding my custom view:

```
[sv addSubview:button];
```

**Comment by aslisabanci** [comment]
Looks pretty clean, good job!

**Comment by pupasani** [comment]
Looks great! One suggestion, be great if could move the badge to the left a bit. Or at least control that offset.

**Comment by lahirumaramba** [comment]
Great work, @enryold !

Quick question. On what license have you released the code? Can we use it in our own apps and fork it to make changes and improvements?

Thanks!

**Comment by enryold** [comment]
@llahiru for sure, you can fork and include it in whatever apps you need it :)
